name: Server CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: create application.yml
        run: |
          cd ./src/main
          mkdir resources && cd $_
          touch ./application.yml
          echo "$APPLICATION" > ./application.yml
        env:
          APPLICATION: ${{ secrets.APPLICATION }}

      - name: give executive authority to gradlew
        run: chmod +x gradlew

      - name: build gradlew
        run: ./gradlew clean build -x test

      - name: build docker image and push to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}

      - name: Deploy to Dev
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.GCP_SSH_USERNAME }}
          host: ${{ secrets.GCP_SSH_HOST }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: ${{ secrets.GCP_SSH_PORT }}
          source: "./scripts/deploy.sh"
          target: "/home/ubuntu/"

      - name: Execute deploy script on remote server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.GCP_SSH_USERNAME }}
          host: ${{ secrets.GCP_SSH_HOST }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: ${{ secrets.GCP_SSH_PORT }}
          script: |
            chmod +x /home/ubuntu/deploy.sh
            /home/ubuntu/deploy.sh

      - name: ✔️ send docker-compose.yml to EC2 server
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.GCP_SSH_USERNAME }}
          host: ${{ secrets.GCP_SSH_HOST }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: ${{ secrets.GCP_SSH_PORT }}
          source: "./docker-compose.yml"
          target: "/home/ubuntu/"

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: ✔️ checkout
        uses: actions/checkout@v3

      - name: ✔️ pull docker image from docker hub and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.GCP_SSH_USERNAME }}
          host: ${{ secrets.GCP_SSH_HOST }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
            chmod 777 ./scripts/deploy.sh
            cp ./scripts/deploy.sh ./deploy.sh
            ./deploy.sh
            docker image prune -f
